### ISSUE TITLE
Problems setting up a dev directory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dfkthf125/sawbuck#59]
```
$ mkdir syzygy
$ cd syzygy
$ gclient config http://sawbuck.googlecode.com/svn/trunk/
$ gclient sync
...
Syncing projects:  95% (21/22), done.ird_party/googleappengine

________ running 'C:\src\syzygy\depot_tools\python_bin\python.exe 
src/build/gyp_chromium src/sawbuck/sawbuck.gyp' in 'C:\src\syzygy'
Enabled Psyco JIT.
Updating projects from gyp files...
Traceback (most recent call last):
  File "src/build/gyp_chromium", line 171, in <module>
    sys.exit(gyp.main(args))
  File "C:\src\syzygy\src\tools\gyp\pylib\gyp\__init__.py", line 471, in main
    options.circular_check)
  File "C:\src\syzygy\src\tools\gyp\pylib\gyp\__init__.py", line 111, in Load
    depth, generator_input_info, check, circular_check)
  File "C:\src\syzygy\src\tools\gyp\pylib\gyp\input.py", line 2383, in Load
    depth, check)
  File "C:\src\syzygy\src\tools\gyp\pylib\gyp\input.py", line 361, in LoadTargetBuildFile
    includes, True, check)
  File "C:\src\syzygy\src\tools\gyp\pylib\gyp\input.py", line 208, in LoadOneBuildFile
    raise Exception("%s not found (cwd: %s)" % (build_file_path, os.getcwd()))
Exception: src\sawbuck\sawbuck.gyp not found (cwd: C:\src\syzygy) while trying 
to load src\sawbuck\sawbuck.gyp
Error: Command C:\src\syzygy\depot_tools\python_bin\python.exe 
src/build/gyp_chromium src/sawbuck/sawbuck.gyp returned non-zero exit status 1 
in C:\src\syzygy

$ dir /B
.gclient
depot_tools
src
trunk

Probably the problem is that it has checked out sawbuck into trunk/ rather than 
src/
```

Original issue reported on code.google.com by `timurrrr@google.com` on 6 Sep 2012 at 10:48

**Comment by GoogleCodeExporter** [comment]
```
FTR, I've used the http://code.google.com/p/sawbuck/wiki/SyzygyDevelopmentGuide 
wiki page.
```

Original comment by `timurrrr@google.com` on 6 Sep 2012 at 10:51

**Comment by GoogleCodeExporter** [comment]
```
I've copied everything from trunk/ to src/ (merging any pair folders with the 
same name) and replaced "trunk" with "src" in the .gclient file and now it 
looks mostly fine.
Would be nice if the problem wasn't happening in the first place
```

Original comment by `timurrrr@google.com` on 6 Sep 2012 at 10:55

**Comment by GoogleCodeExporter** [comment]
```
This is due to an error in the sample command line. It should read

  gclient config http://sawbuck.googlecode.com/svn/trunk/ --name=src

so that things get put in 'src' immediately, rather than the inferred name, 
trunk. I've updated the wiki. Thanks for pointing this out!
```

Original comment by `chri...@chromium.org` on 6 Sep 2012 at 1:41

**Comment by GoogleCodeExporter** [comment]
```
Thanks!
You can probably close the issue now if you've checked it works.
```

Original comment by `timurrrr@google.com` on 6 Sep 2012 at 1:44

**Comment by GoogleCodeExporter** [comment]
Original comment by `chri...@chromium.org` on 6 Sep 2012 at 2:11
- Changed state: **Fixed**
